function Work() {
    return(
        <section id="work">
            <h1>Experience</h1>
            <h2>Developer Analyst Intern <span class="company-name">| Bombardier</span></h2>
            <h4>SEPT 2022 - DEC 2022</h4>
            <ul className="work-description">
                <li>Automated the business travel assessment and the internship assessment process for the Legal Services
                    team by designing a user-friendly Microsoft PowerApp that allows employees and interns to upload
                    necessary documents and respond to inquiries associated with their respective requests.</li>
                <li>Reduced manual intervention and follow-ups by the legal services team by connecting the app to a Power
                    Automate flow, allowing notifications to be sent to the team upon successful completion of requests and
                    allowing customized legal documents to be generated by populating Microsoft Word templates.</li>
            </ul>
        </section>
    )

}

export default Work